// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzQyS4RMueIEqkEV3_xXW30KtEQ-Dg9k',
    appId: '1:238207412063:web:7662f18911691f5c33f8ea',
    messagingSenderId: '238207412063',
    projectId: 'cut-sports-14b3f',
    authDomain: 'cut-sports-14b3f.firebaseapp.com',
    storageBucket: 'cut-sports-14b3f.firebasestorage.app',
    measurementId: 'G-46WRGT0YSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6AMo0zih9pf1FydKsGQ7EGFBRT8Gs0ME',
    appId: '1:238207412063:android:0e3ca8a1a167354c33f8ea',
    messagingSenderId: '238207412063',
    projectId: 'cut-sports-14b3f',
    storageBucket: 'cut-sports-14b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCUaxssZjskFMkzwQynRAjiMX9LLj2gCU',
    appId: '1:238207412063:ios:925ee10f6646d02f33f8ea',
    messagingSenderId: '238207412063',
    projectId: 'cut-sports-14b3f',
    storageBucket: 'cut-sports-14b3f.firebasestorage.app',
    iosBundleId: 'com.example.srcProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCUaxssZjskFMkzwQynRAjiMX9LLj2gCU',
    appId: '1:238207412063:ios:925ee10f6646d02f33f8ea',
    messagingSenderId: '238207412063',
    projectId: 'cut-sports-14b3f',
    storageBucket: 'cut-sports-14b3f.firebasestorage.app',
    iosBundleId: 'com.example.srcProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSzQyS4RMueIEqkEV3_xXW30KtEQ-Dg9k',
    appId: '1:238207412063:web:5f1ecf8d7333a10233f8ea',
    messagingSenderId: '238207412063',
    projectId: 'cut-sports-14b3f',
    authDomain: 'cut-sports-14b3f.firebaseapp.com',
    storageBucket: 'cut-sports-14b3f.firebasestorage.app',
    measurementId: 'G-GS3LK0HRFW',
  );

}